import { Routes } from '@angular/router';
import { Home } from './home/home';
import { Login } from './login/login';
import { RegistroComponent } from './registro/registro';  
import { Bienvenido } from './bienvenido/bienvenido';
import { Planear } from './planear/planear'; 
import { PaginaPrincipal } from './pagina-principal/pagina-principal';
import { Noruega } from './noruega/noruega';
import { Alemania } from './alemania/alemania';
import { Francia } from './francia/francia';
import { RedesSociales } from './redes-sociales/redes-sociales';
import { Oslo } from './oslo/oslo';
import { Bergen } from './bergen/bergen';
import { Stavanger } from './stavanger/stavanger';
import { QueOfrecemos } from './que-ofrecemos/que-ofrecemos';
import { Berlin } from './berlin/berlin';
import { Bremen } from './bremen/bremen';
import { Lubeck } from './lubeck/lubeck';
import { Marsella } from './marsella/marsella';
import { Toulouse } from './toulouse/toulouse';
import { Tours } from './tours/tours';
import { Valoraciones1 } from './valoraciones/valoraciones1';
import { ValoracionesGenerales } from './valoraciones-generales/valoraciones-generales';
import { Dashboard } from './dashboard/dashboard'; 
import { Gestionaractividades } from './gestionaractividades/gestionaractividades';

export const routes: Routes = [
  { path: '', component: Home },
  { path: 'login', component: Login },
  { path: 'registro', component: RegistroComponent },  
  { path: 'bienvenido', component: Bienvenido },
  { path: 'que-ofrecemos', component: QueOfrecemos },
  { path: 'planear', component: Planear },
  { path: 'pagina-principal', component: PaginaPrincipal },
  { path: 'noruega', component: Noruega },
  { path: 'alemania', component: Alemania },
  { path: 'francia', component: Francia },
  { path: 'redes-sociales', component: RedesSociales },
  { path: 'oslo', component: Oslo },
  { path: 'bergen', component: Bergen },
  { path: 'stavanger', component: Stavanger },
  { path: 'berlin', component: Berlin },
  { path: 'bremen', component: Bremen },
  { path: 'lubeck', component: Lubeck },
  { path: 'marsella', component: Marsella },
  { path: 'toulouse', component: Toulouse },
  { path: 'tours', component: Tours },  
  { path: 'valoraciones/:destino', component: Valoraciones1 },
  { path: 'tours', component: Tours },
  { path: 'valoraciones-generales', component: ValoracionesGenerales },
  { path: 'dashboard', component: Dashboard },
  { path: 'gestionaractividades', component: Gestionaractividades },
];