import { Routes } from '@angular/router';
import { Home } from './home/home';
import { Login } from './login/login';
import { Registro } from './registro/registro';
import { Bienvenido } from './bienvenido/bienvenido';
import { QueOfrecemosComponent } from './que-ofrecemos/que-ofrecemos';
import { Planear } from './planear/planear'; 
import { PaginaPrincipal } from './pagina-principal/pagina-principal';
import { Dashboard } from './admin/dashboard/dashboard';
import { Noruega } from './noruega/noruega';
import { Alemania } from './alemania/alemania';
import { Francia } from './francia/francia';
import { RedesSociales } from './redes-sociales/redes-sociales';
import { Oslo } from './oslo/oslo';

export const routes: Routes = [
  { path: '', component: Home },
  { path: 'login', component: Login },
  { path: 'registro', component: Registro },
  { path: 'bienvenido', component: Bienvenido },
  { path: 'que-ofrecemos', component: QueOfrecemosComponent },
  { path: 'planear', component: Planear },
  { path: 'pagina-principal', component: PaginaPrincipal },
  { path: 'admin', component: Dashboard },
  { path: 'noruega', component: Noruega },
  { path: 'alemania', component: Alemania },
  { path: 'francia', component: Francia },
  { path: 'redes-sociales', component: RedesSociales },
  { path: 'oslo', component: Oslo }
];