version: '3.8'

services:
  # Base de datos MySQL
  mysql:
    image: mysql:5.7
    container_name: trip_n_joy_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: trip_n_joy_db
      MYSQL_ROOT_PASSWORD: root_123456
      MYSQL_USER: trip_user
      MYSQL_PASSWORD: trip_pass_123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - trip_net

  # Backend PHP-FPM con Laravel
  php-fpm:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: trip_n_joy_php
    restart: unless-stopped
    environment:
      - "DB_CONNECTION=mysql"
      - "DB_HOST=mysql"
      - "DB_PORT=3306"
      - "DB_DATABASE=trip_n_joy_db"
      - "DB_USERNAME=trip_user"
      - "DB_PASSWORD=trip_pass_123"
    volumes:
      - ./backend:/var/www/backend
    networks:
      - trip_net
    depends_on:
      - mysql

  # Servidor Web Nginx
  webserver:
    image: nginx:alpine
    container_name: trip_n_joy_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/backend
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - trip_net
    depends_on:
      - php-fpm

networks:
  trip_net:
    driver: bridge

volumes:
  mysql_data: